app:main.o bubble.o insertion.o
	gcc main.o bubble.o insertion.o -o app
main.o:main.c
	gcc -c main.c -o main.o
bubble.o:bubble.c
	gcc -c bubble.c -o bubble.o
insertion.o:insertion.c
	gcc -c insertion.c -o insertion.o
clean:
	rm *.o

